create table public.user_account (
    id integer generated by default as identity primary key,
    username varchar(20) not null unique,
    password varchar(255) not null,
    email varchar(50) not null unique,
    "online_ID" varchar(20) not null unique,
    is_active boolean not null default true
);

create table public.friends (
    id integer generated by default as identity primary key,
    user_id integer not null references public.user_account(id) on delete cascade,
    name varchar(20) not null,
    "online_ID" varchar(20) not null
);

create table public.game_modes (
    id integer generated by default as identity primary key,
    mode_name varchar(20) not null,
    constraint game_mode_name_check check (mode_name is not null)
);

create table public.builds (
    id integer generated by default as identity primary key,
    user_id integer references public.user_account(id) on delete cascade,
    friend_id integer references public.friends(id) on delete cascade,
    build_name varchar(20) not null,
    preferred_position varchar(15) not null,
    constraint build_user_info_check check ((user_id is not null) <> (friend_id is not null))
);

create table public.games (
    id integer generated by default as identity primary key,
    user_id integer not null references public.user_account(id) on delete cascade,
    game_mode_id integer not null references public.game_modes(id) on delete cascade,
    build_id integer references public.builds(id) on delete set null,
    date_time timestamptz not null,
    result varchar(1) not null,
    points_for integer not null,
    q1_points_for integer not null,
    q2_points_for integer not null,
    q3_points_for integer not null,
    q4_points_for integer not null,
    points_against integer not null,
    q1_points_against integer not null,
    q2_points_against integer not null,
    q3_points_against integer not null,
    q4_points_against integer not null,
    constraint game_info_check check (
        game_mode_id is not null and user_id is not null and date_time is not null
        and result is not null and points_for is not null
        and q1_points_for is not null and q2_points_for is not null
        and q3_points_for is not null and q4_points_for is not null
        and points_against is not null and q1_points_against is not null
        and q2_points_against is not null and q3_points_against is not null
        and q4_points_against is not null
    )
);

create table public.player_statlines (
    id integer generated by default as identity primary key,
    game_id integer not null references public.games(id) on delete cascade,
    build_id integer references public.builds(id) on delete cascade,
    friend_id integer references public.friends(id) on delete cascade,
    friend_build_id integer references public.builds(id) on delete cascade,
    points integer not null,
    rebounds integer not null,
    assists integer not null,
    steals integer not null,
    blocks integer not null,
    fouls integer not null,
    turnovers integer not null,
    field_goals_made integer not null,
    field_goals_attempted integer not null,
    three_pointers_made integer not null,
    three_pointers_attempted integer not null,
    free_throws_made integer not null,
    free_throws_attempted integer not null,
    position varchar(10),
    opponent varchar(50),
    constraint statline_player_type_check check (
        (build_id is not null and friend_id is null and friend_build_id is null)
        or (build_id is null and friend_id is not null and friend_build_id is not null)
    ),
    constraint unique_friend_statline_per_game unique (game_id, friend_id)
);

create table public.team_statlines (
    id integer generated by default as identity primary key,
    game_id integer not null references public.games(id) on delete cascade,
    points integer not null,
    rebounds integer not null,
    assists integer not null,
    steals integer not null,
    blocks integer not null,
    fouls integer not null,
    turnovers integer not null,
    field_goals_made integer not null,
    field_goals_attempted integer not null,
    three_pointers_made integer not null,
    three_pointers_attempted integer not null,
    free_throws_made integer not null,
    free_throws_attempted integer not null,
    constraint unique_team_statline_per_game unique (game_id)
);

create table public.box_score_images (
    id integer generated by default as identity primary key,
    user_id integer not null references public.user_account(id) on delete cascade,
    game_id integer references public.games(id) on delete cascade,
    original_path varchar not null,
    processed_path varchar,
    created_at timestamp
);

create index friends_user_id_idx on public.friends(user_id);
create index builds_user_id_idx on public.builds(user_id);
create index builds_friend_id_idx on public.builds(friend_id);
create index games_user_id_idx on public.games(user_id);
create index games_game_mode_id_idx on public.games(game_mode_id);
create index games_build_id_idx on public.games(build_id);
create index player_statlines_game_id_idx on public.player_statlines(game_id);
create index player_statlines_build_id_idx on public.player_statlines(build_id);
create index player_statlines_friend_id_idx on public.player_statlines(friend_id);
create index player_statlines_friend_build_id_idx on public.player_statlines(friend_build_id);
create index team_statlines_game_id_idx on public.team_statlines(game_id);
create index box_score_images_user_id_idx on public.box_score_images(user_id);
create index box_score_images_game_id_idx on public.box_score_images(game_id);
