services:
  - type: web
    name: twok-stats-website
    runtime: docker
    plan: free
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://shitchman.github.io